deverver:
	cd output && devserver --reload
simple_md_raw:
	elepages --source ./pages/simple_mds  -vvv

simple_md_simple_template:
	elepages --source ./pages/simple_mds  --config ./stages/simple_template.yaml -vvv

shadowed_md_simple_template:
	elepages --source ./pages/shadowed_mds  --config ./stages/simple_template.yaml -vvv

shadowed_md_multilevel_template:
	elepages --source ./pages/shadowed_mds  --config ./stages/multi_level_template.yaml -vvv

shadowed_md_partial_template:
	elepages --source ./pages/shadowed_mds  --config ./stages/partial_template.yaml -vvv