deverver:
	cd output && devserver --reload

example_1:
	# simple md generation
	elepages --source ./pages/1_mds  -vvv

example_2:
	# simple md generation with git metadata configuration
	elepages --source ./pages/1_mds --git-path ../ -vvv