mod compose_stage;
mod compose_stage_test;
mod copy_stage;
mod copy_stage_test;
mod git_authors;
mod git_authors_test;
mod handlebars_stage;
mod handlebars_stage_test;
mod indexes_stage;
mod indexes_stage_test;
mod md_stage;
mod md_stage_test;
mod metadata_tree;
mod metadata_tree_test;
mod sequence_stage;
mod shadow_pages;
mod shadow_pages_test;
mod stage;
#[cfg(test)]
mod test_stage;
mod union_stage;
mod union_stage_test;

pub use self::compose_stage::*;
pub use self::copy_stage::*;
pub use self::git_authors::*;
pub use self::handlebars_stage::*;
pub use self::indexes_stage::*;
pub use self::md_stage::*;
pub use self::sequence_stage::*;
pub use self::shadow_pages::*;
pub use self::stage::*;
pub use self::union_stage::*;
